// Auto-generated by tools/gen_build_info.py — DO NOT EDIT
#pragma once
static const struct { const char *name; const char *ver; } kLibDeps[] = {
  { "AceRoutine", "^1.5.1" },
  { "ArduinoJson", "^7.0.0" },
  { "EspSoftwareSerial", "^8.2.0" },
  { "NmraDcc", "^2.0.17" },
  { "U8g2", "^2.36.18" },
  { nullptr, nullptr }
};
