#!/usr/bin/env python3
"""
Build embedded data files (JSON types) as PROGMEM C++ headers.

Converts structural JSON files to compressed byte arrays embedded in firmware:
  - lib/MrJ-RailwayFX.local/data/*.json → lib/.../include/generated/embedded_*.h

Similar to build_webui.py but for JSON catalogs (types, i2c_known).
Files are gzipped and served with Content-Encoding: gzip by the API.

Called automatically by PlatformIO before build (see platformio.ini extra_scripts).

@project MrJ-ArduinoRailwayFX
@license MIT License — Copyright (c) 2026 HO44 PROJECT
"""

# PlatformIO hook support
try:
    Import("env")
    IS_PLATFORMIO = True
except:
    IS_PLATFORMIO = False

import gzip
import json
import re
from pathlib import Path

def minify_json(data: dict) -> str:
    """Minify JSON (remove whitespace)."""
    return json.dumps(data, separators=(',', ':'), ensure_ascii=False)

def read_brand(lib: Path) -> str:
    """Displayed brand name — parsed from MRJFX_PROJECT_NAME in the firmware
    header (single source of truth, see MrJRailwayFX_default.h). Every %%BRAND%%
    token in the JSON catalogs is substituted with it at embed time."""
    hdr = lib / "include" / "MrJRailwayFX_default.h"
    m = re.search(r'#define\s+MRJFX_PROJECT_NAME\s+"([^"]+)"',
                  hdr.read_text(encoding='utf-8'))
    if not m:
        raise RuntimeError("MRJFX_PROJECT_NAME not found in MrJRailwayFX_default.h")
    return m.group(1)

def json_to_progmem(input_path: Path, output_path: Path, var_name: str, brand: str = ""):
    """Convert JSON file to gzipped PROGMEM C++ header."""

    # Read and minify JSON
    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    minified = minify_json(data)
    if brand:
        minified = minified.replace('%%BRAND%%', brand)
    original_size = len(minified.encode('utf-8'))

    # Gzip compress — mtime=0 so output is reproducible (no embedded timestamp
    # → the generated header only changes when the source JSON actually changes).
    compressed = gzip.compress(minified.encode('utf-8'), compresslevel=9, mtime=0)
    compressed_size = len(compressed)

    # Generate C++ header
    header = f"""/**
 * @file {output_path.name}
 * @brief Embedded {input_path.stem} catalog (gzipped JSON in PROGMEM).
 *
 * Auto-generated by tools/build_embedded_data.py — DO NOT EDIT MANUALLY.
 * Source: {input_path.relative_to(input_path.parents[3])}
 *
 * Original size: {original_size} bytes
 * Compressed:    {compressed_size} bytes ({100*compressed_size//original_size}% of original)
 *
 * Served by /api/{input_path.stem.replace('_', '-')} with Content-Encoding: gzip
 *
 * @project MrJ-ArduinoRailwayFX
 * @license MIT License — Copyright (c) 2026 HO44 PROJECT
 */

#pragma once

#include <Arduino.h>

// Gzipped JSON data embedded in flash (PROGMEM)
const uint8_t {var_name}_GZ[] PROGMEM = {{
"""

    # Write bytes as hex array (16 bytes per line)
    for i in range(0, len(compressed), 16):
        chunk = compressed[i:i+16]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        header += f'  {hex_bytes},\n'

    # Remove trailing comma
    header = header.rstrip(',\n') + '\n'

    header += f"""}};

const size_t {var_name}_GZ_LEN = sizeof({var_name}_GZ);
"""

    # Write header file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header)

    print(f"✅ {input_path.name:20} → {output_path.name:30} "
          f"({original_size:6} → {compressed_size:6} bytes, {100*compressed_size//original_size:2}%)")

def board_pincounts_to_header(input_path: Path, output_path: Path):
    """Emit a tiny uncompressed type→pin_count map for SPI board types.

    The full board_types catalog is gzipped in PROGMEM for the WebUI, but the
    firmware still needs structural pin counts to size 74HC595 daisy-chain cards
    when a board entry omits "pin_count".  Only spi_master_only types are
    emitted — they are the only ones DeviceFactory sizes from this table.
    """
    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    entries = []
    for type_name, definition in data.items():
        if type_name.startswith('$') or not isinstance(definition, dict):
            continue
        if definition.get('busType') != 'spi_master_only':
            continue
        pin_count = sum(1 for p in definition.get('pins', []) if 'wiring' in p)
        entries.append((type_name, pin_count))

    header = f"""/**
 * @file {output_path.name}
 * @brief Structural pin counts for SPI board types (uncompressed, firmware-side).
 *
 * Auto-generated by tools/build_embedded_data.py — DO NOT EDIT MANUALLY.
 * Source: {input_path.relative_to(input_path.parents[3])}
 *
 * The full board_types catalog is gzipped in PROGMEM for the WebUI
 * (embedded_board_types.h).  The firmware only needs SPI pin counts to size
 * 74HC595 daisy-chain cards when a board omits "pin_count", so this compact
 * uncompressed table is emitted alongside it and passed to DeviceFactory::load().
 *
 * @project MrJ-ArduinoRailwayFX
 * @license MIT License — Copyright (c) 2026 HO44 PROJECT
 */

#pragma once

#include "config/BoardPinCount.h"

// type → number of "wiring" pins, for spi_master_only board types only.
const BtPinCount BOARD_PIN_COUNTS[] = {{
"""
    for type_name, pin_count in entries:
        header += f'  {{ "{type_name}", {pin_count} }},\n'
    header += """};

const uint8_t BOARD_PIN_COUNTS_LEN = sizeof(BOARD_PIN_COUNTS) / sizeof(BOARD_PIN_COUNTS[0]);
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header)

    print(f"✅ {input_path.name:20} → {output_path.name:30} "
          f"({len(entries)} SPI board types)")

def main():
    """Build all embedded data files."""

    # This script lives in the library's own tools/ dir, so resolve paths from
    # the library root — keeps the library self-contained (it regenerates its own
    # embedded headers, which are gitignored). Works as a PlatformIO hook and
    # standalone (python3 tools/build_embedded_data.py).
    if IS_PLATFORMIO:
        lib = Path(env.get("PROJECT_DIR")) / "lib" / "MrJ-RailwayFX.local"
    else:
        lib = Path(__file__).resolve().parent.parent  # tools/ → library root

    lib_data_dir = lib / "data"
    output_dir = lib / "include" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    brand = read_brand(lib)  # substituted into every %%BRAND%% token below

    files = [
        ("board_types.json",  "BOARD_TYPES"),
        ("device_types.json", "DEVICE_TYPES"),
        ("bus_types.json",    "BUS_TYPES"),
        ("i2c_known.json",    "I2C_KNOWN"),
    ]

    print("=" * 80)
    print("Building embedded data files (JSON → PROGMEM)...")
    print("=" * 80)

    for filename, var_name in files:
        input_path = lib_data_dir / filename
        output_path = output_dir / f"embedded_{filename.replace('.json', '')}.h"

        if not input_path.exists():
            print(f"⚠️  WARNING: {input_path} not found, skipping")
            continue

        json_to_progmem(input_path, output_path, var_name, brand)

    # Firmware-side structural pin-count map (uncompressed — used by DeviceFactory
    # to size SPI cards when a board config omits "pin_count").
    board_types_path = lib_data_dir / "board_types.json"
    if board_types_path.exists():
        board_pincounts_to_header(
            board_types_path,
            output_dir / "embedded_board_pincounts.h",
        )

    print("=" * 80)
    print("Build complete! Headers ready in lib/include/generated/")
    print("=" * 80)

# Run main function
main()

# Register as PlatformIO pre-build action if running as hook
if IS_PLATFORMIO:
    env.Execute(lambda *args, **kwargs: None)  # Hook already executed via main() above
