"""
gen_build_info.py — PlatformIO pre-build script.

Writes include/generated/build_info.h with:
  - the declared library dependencies (name + version constraint), so
    DeviceStatusApi can expose them at runtime via /api/status (web UI
    "Libraries" card).
  - a kFirmwareBuildDate string stamped with the current date/time.

The dependency list comes straight from PlatformIO's *resolved* project options
via env.GetProjectOption("lib_deps"). PlatformIO itself handles `extends`,
${section.option} interpolation and the global [env] defaults — so this script
never parses platformio.ini by hand and can't drift from how the build actually
resolves the environment.

kFirmwareBuildDate must NOT come from __DATE__ __TIME__ in a .cpp file: those macros
are stamped when THAT translation unit is compiled, and SCons only recompiles
a .cpp when it (or an #include dependency) has a newer mtime than its cached
.o — so the embedded timestamp can silently stay frozen across builds that
don't touch that file, even though the overall link+flash succeeds (#108).
This script runs as a `pre:` extra_script, so it re-executes on every build
regardless of SCons' .o cache, keeping the timestamp meaningful.
"""

Import("env")  # noqa: F821 — PlatformIO global

import os
from datetime import datetime

_LIB = os.path.join(env.subst("$PROJECT_DIR"), "lib", "MrJ-RailwayFX.local")  # noqa: F821
_OUT = os.path.join(_LIB, "include", "generated", "build_info.h")


def _parse_dep(spec):
    """'owner/Name@constraint' → ('Name', 'constraint') or (None, None)."""
    spec = spec.strip()
    if not spec or spec.startswith((";", "#")):
        return None, None
    at = spec.find("@")
    constraint = spec[at + 1:].strip() if at >= 0 else ""
    base = spec[:at].strip() if at >= 0 else spec
    slash = base.rfind("/")
    name = base[slash + 1:].strip() if slash >= 0 else base.strip()
    return name, constraint


# Resolved by PlatformIO for the active env: follows `extends`, expands ${...},
# merges [env]. Returns a list on current PlatformIO; tolerate a string too.
deps = env.GetProjectOption("lib_deps", [])  # noqa: F821
if isinstance(deps, str):
    deps = deps.splitlines()

entries = [_parse_dep(s) for s in deps]
entries = sorted([(n, c) for n, c in entries if n], key=lambda x: x[0].lower())

build_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

os.makedirs(os.path.dirname(_OUT), exist_ok=True)
with open(_OUT, "w") as f:
    f.write("// Auto-generated by tools/gen_build_info.py — DO NOT EDIT\n")
    f.write("#pragma once\n")
    f.write('static const char *kFirmwareBuildDate = "{}";\n'.format(build_date))
    f.write("static const struct { const char *name; const char *ver; } kLibDeps[] = {\n")
    for name, constraint in entries:
        f.write('  {{ "{}", "{}" }},\n'.format(name, constraint))
    f.write("  { nullptr, nullptr }\n")
    f.write("};\n")

print("[gen_build_info] {} entries (env={}) → {}".format(
    len(entries), env.subst("$PIOENV"), _OUT))  # noqa: F821
